In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("All libraries installed successfully!")

Matplotlib is building the font cache; this may take a moment.

All libraries installed successfully!

In [2]:
# Create a small dictionary containing student information
data = {
    "Name": ["John", "Mary", "Alex", "Sarah", "David"],
    "Age": [20, 21, 19, 22, 20],
    "Score": [75, 88, 65, 92, 70]
}

# Convert the dictionary into a pandas DataFrame
df = pd.DataFrame(data)

# Display the data
df

    Name  Age  Score
0   John   20     75
1   Mary   21     88
2   Alex   19     65
3  Sarah   22     92
4  David   20     70

In [3]:
# Display the first 5 rows of the dataset
df.head()

    Name  Age  Score
0   John   20     75
1   Mary   21     88
2   Alex   19     65
3  Sarah   22     92
4  David   20     70

In [4]:
# Show the number of rows and columns
print("Shape of the data:", df.shape)

# Show the names of the columns
print("Columns:", df.columns.tolist())

# Show information about the data types
df.info()

Shape of the data: (5, 3)
Columns: ['Name', 'Age', 'Score']
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     5 non-null      int64
 2   Score   5 non-null      int64
dtypes: int64(2), str(1)
memory usage: 252.0 bytes

In [5]:
# Calculate the average score of all students
average_score = df["Score"].mean()

# Display the result
print("Average score:", average_score)

Average score: 78.0

In [6]:
# Find the highest score
highest_score = df["Score"].max()

# Find the lowest score
lowest_score = df["Score"].min()

print("Highest score:", highest_score)
print("Lowest score:", lowest_score)

Highest score: 92
Lowest score: 65

In [7]:
# Find students who scored more than 70
high_scores = df[df["Score"] > 70]

# Display the students
high_scores

    Name  Age  Score
0   John   20     75
1   Mary   21     88
3  Sarah   22     92

In [8]:
# Select students whose age is exactly 20
students_20 = df[df["Age"] == 20]

students_20

    Name  Age  Score
0   John   20     75
4  David   20     70

In [9]:
# Create a new column called "Passed"
# A student passes if their score is 50 or higher
df["Passed"] = df["Score"] >= 50

# Display the updated DataFrame
df

    Name  Age  Score  Passed
0   John   20     75    True
1   Mary   21     88    True
2   Alex   19     65    True
3  Sarah   22     92    True
4  David   20     70    True

In [10]:
# Sort students from highest score to lowest score
sorted_df = df.sort_values(by="Score", ascending=False)

# Display the sorted data
sorted_df

    Name  Age  Score  Passed
3  Sarah   22     92    True
1   Mary   21     88    True
0   John   20     75    True
4  David   20     70    True
2   Alex   19     65    True

In [ ]:
# Create a bar chart showing each student's score
plt.bar(df["Name"], df["Score"])

# Add a title to the graph
plt.title("Student Scores")

# Label the x-axis
plt.xlabel("Student")

# Label the y-axis
plt.ylabel("Score")

# Display the graph
plt.show()